### ISSUE TITLE
Bluetooth Battery Bar Issue

### ISSUE THREAD

**Issue by sjet3** [gschrader/ubersicht-bluetooth-battery-bar#1]
Glen Schrader
gschrader

The trackpad battery indicator matches the Mavericks system report from the Bluetooth menu item but the keyboard percentage is way off. I didn't change the script, and don't understand the debug console (I'm really new at this). Any suggestions? 

width        = '367px'
barHeight    = '36px'
labelColor   = '#fff'
usedColor    = '#d7051d'
freeColor    = '#525252'
bgColor      = '#fff'
borderRadius = '3px'
bgOpacity    = 0.9

command: """
kbatt=`ioreg -n "AppleBluetoothHIDKeyboard" | grep BatteryPercent | tail -1 | awk -F"=" {'print $2'}` &&
if [ ${#kbatt} -gt 0 ]; then echo "Keyboard$kbatt%"; fi &&
tbatt=`ioreg -c BNBTrackpadDevice | grep BatteryPercent | tail -1 | awk -F"=" {'print $2'}` &&
if [ ${#tbatt} -gt 0 ]; then echo "Trackpad$tbatt%"; fi &&
mbatt=`ioreg -c BNBMouseDevice | grep BatteryPercent | tail -1 | awk -F"=" {'print $2'}` &&
if [ ${#mbatt} -gt 0 ]; then echo "Mouse$mbatt%"; fi;
"""

refreshFrequency: 20000

style: """
  // Change bar height
  bar-height = 6px

  // Align contents left or right
  widget-align = left

  // Position this where you want
  top 100px
  left 1000px

  color #fff
  font-family Helvetica Neue
  background rgba(#000, .5)
  padding 10px 10px 15px
  border-radius 5px

  .container
    width: 300px
    text-align: widget-align
    position: relative
    clear: both

  .container:not(:first-child)
    margin-top: 20px

  .widget-title
    text-align: widget-align

  .widget-title, p
    font-size 10px
    text-transform uppercase
    font-weight bold

  .label
    float: right

  .bar-container
    width: 100%
    height: bar-height
    border-radius: bar-height
    float: widget-align
    clear: both
    background: rgba(#fff, .5)
    position: absolute
    margin-bottom: 5px

  .bar
    height: bar-height
    float: widget-align
    transition: width .2s ease-in-out

  .bar:first-child
    if widget-align == left
      border-radius: bar-height 0 0 bar-height
    else
      border-radius: 0 bar-height bar-height 0

  .bar:last-child
    if widget-align == right
      border-radius: bar-height 0 0 bar-height
    else
      border-radius: 0 bar-height bar-height 0

  .bar-used
    background: rgba(#c00, .5)
"""

renderInfo: (name, pctg) -> """
  <div class="container">
    <div class="widget-title">#{name} <span class="label">#{pctg}</span></div>
    <div class="bar-container">
      <div class="bar bar-used" style="width: #{pctg}"></div>
    </div>
  </div>
"""

update: (output, domEl) ->
  devices = output.split('\n')
  $(domEl).html ''

  for device, i in devices
    args = device.split(' ')
    if (args[1])
      args[1] = args[1..].join(' ')
      $(domEl).append @renderInfo(args...)

  $(domEl).append ''

**Comment by gschrader** [comment]
I didn't realize my values are different as well, I'll see if I can figure out why.

**Comment by sjet3** [comment]
Hi Glen,
Thanks for answering back! I've had significant performance problems,
troubleshooting not making much of a difference. Is this meant to run on El
Capitan?
Best,
Suzanne

Thanks,
Suzanne
(828) 280-0081

**Comment by gschrader** [comment]
It should run in El Capitan just fine, do you have other widgets in Ubersicht that might be causing your performance problems?  You can also change the refreshFrequency so it doesn't update as frequently.

As for the wrong values, I think I've found a command that will report the same values as the Bluetooth menu.  Can you run the following in Terminal to see if it matches for you?

`
system_profiler SPBluetoothDataType | grep -E "Battery|Services"
`

**Comment by sjet3** [comment]
Been pretty tied up, will tackle later today. I'm running Yosemite—think
that's okay?

On Saturday, November 14, 2015, Glen Schrader notifications@github.com
wrote:

> It should run El Capitan just fine, do you have other widgets in Ubersicht
> that might be causing your performance problems? You can also change the
> refreshFrequency so it doesn't update as frequently.
> 
> As for the wrong values, I think I've found a command that will report the
> same values as the Bluetooth menu. Can you run the following in Terminal to
> see if it matches for you?
> 
> system_profiler SPBluetoothDataType | grep -E "Battery|Services"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gschrader/ubersicht-bluetooth-battery-bar/issues/1#issuecomment-156743720
> .

## 

Sent from my iPhone

**Comment by gschrader** [comment]
I would guess that Yosemite should work fine. I have updated it to use the new method, you can download it [here](https://raw.githubusercontent.com/gschrader/ubersicht-bluetooth-battery-bar/master/bluetooth-battery-bar.widget.zip).
