### ISSUE TITLE
Multiple oddities

### ISSUE THREAD

**Issue by rickjtaylor** [gschrader/ubersicht-bluetooth-battery-bar#2]
Take a look at this screen grab to see a few odd things:
1. The names of the devices partially left and right justified. Those names are:
2. Magic Keyboard
3. Magic Trackpad 2
4. No colored bar for either.
5. All that whacky stuff at the bottom and the extra bar.

Thanks!

![grab](https://cloud.githubusercontent.com/assets/2989492/11230343/cf777fd6-8d52-11e5-8d59-12ab9798b664.jpg)

**Comment by gschrader** [comment]
Can you run the following in terminal and give me the results:
`system_profiler SPBluetoothDataType | grep -E "Battery|Services"`

I'm guessing the other bluetooth devices are causing the widget grief.

**Comment by rickjtaylor** [comment]
Here you go:

ricks-imac:~ Rick$ system_profiler SPBluetoothDataType | grep -E "Battery|Services"
              Services: Magic Keyboard
              Battery Level: 84%
              Services: Magic Trackpad 2
              Battery Level: 88%
              Services: 
              Services: 
              Services: 
              Services: Headset Audio Gateway, Group Ad-hoc Network Service, A2DP Audio Source, AVRCP Target, Apple Macintosh Attributes, Bluetooth-Incoming-Port, Hands Free Audio Gateway
              Services: 
      Services:
ricks-imac:~ Rick$

**Comment by gschrader** [comment]
the latest update will hopefully work better

**Comment by rickjtaylor** [comment]
works like a charm!!!

**Comment by gschrader** [comment]
Nice!
