### ISSUE TITLE
system_profiler throws exception on macOS High Sierra

### ISSUE THREAD

**Issue by imranzahid01** [gschrader/ubersicht-bluetooth-battery-bar#3]
The widget was working great, but as soon as I updated my OS to High Sierra, ```system_profiler SPBluetoothDataType``` started throwing exceptions which are visible in the widget.
You have any idea how to avoid this?

```
system_profiler[5781:108932] Exception NSInvalidArgumentException thrown while decoding IOBluetoothSDPServiceRecord
```

**Comment by gschrader** [comment]
This should now be fixed in 78fc10a9c87bef5b92f81fb452986cdbe5913677
