### ISSUE TITLE
visible only keyboard battery level

### ISSUE THREAD

**Issue by metatron23** [gschrader/ubersicht-bluetooth-battery-bar#4]
Hi!

I have just installed widget. I have 2 Bluetooth devices connected: keyboard, trackpad. But only keyboard is visible. Any idea why?
![screenshot 2018-10-02 at 15 07 51](https://user-images.githubusercontent.com/10022028/46350417-04367e00-c655-11e8-9016-f8e2f9dba21a.png)

**Comment by gschrader** [comment]
I'm not sure why it wouldn't show up. Can you run the following in terminal and give me the results:
`system_profiler SPBluetoothDataType | grep -E "Battery|Services"`
