### ISSUE TITLE
How would I go about renaming my devices?

### ISSUE THREAD

**Issue by ayala** [gschrader/ubersicht-bluetooth-battery-bar#6]
I've changed them un the System Preferences Bluetooth settings but the renames don't reflect in the widget. How could I get simple names like your screenshot?

![screenshot](https://user-images.githubusercontent.com/53095/82450588-e2347e00-9a7a-11ea-9571-f79aea62862e.png)

**Comment by gschrader** [comment]
You might be better off trying the [previous version](https://github.com/gschrader/ubersicht-bluetooth-battery-bar/tree/c3a6d13ae7b0e5fd13231bd8a46105e9497f5b69) that uses ioreg  instead of system_profiler. You can then modify the command that is issued to echo whichever name you'd like.

**Comment by ayala** [comment]
thanks but that version doesn't work on my setup. Not sure if its a Catalina thing. The newer version works fine but lists the full name of the apple peripheral.

Thanks

**Comment by gschrader** [comment]
Ok the only other thing you can try is modify the [command line](https://github.com/gschrader/ubersicht-bluetooth-battery-bar/blob/master/bluetooth-battery-bar.widget/index.coffee#L11) to rename things with `sed` i.e. at the end of the line right after the paste section:

```
 ... paste -d" " - - | sed "s/TEXT YOU WANT REPLACED/Mouse/g"
```

**Comment by ayala** [comment]
Ah! that did it... thank you so much!

Cheers!
