### ISSUE TITLE
Isn't working 

### ISSUE THREAD

**Issue by msilvaaa** [gschrader/ubersicht-bluetooth-battery-bar#8]
After updating my Mac to Monterey version, the widget isn't show in my screen.

**Comment by gschrader** [comment]
Unfortunately I'm stuck on Big Sur as my MBP doesn't support Monterey so I probably won't be able to help until my next hardware upgrade.

**Comment by dvenman** [comment]
Happy to help - all I need is some assistance with the starting point here - https://apple.stackexchange.com/questions/215256/check-the-battery-level-of-connected-bluetooth-headphones-from-the-command-line

"system_profiler" doesn't now return the required data (or at least not in the format needed by the widget) and io_reg appears to, but it's a case of linking the device name to the battery level...

**Comment by gschrader** [comment]
@dvenman yes it seems as though Monterey has changed [things](https://apple.stackexchange.com/questions/439148/how-to-get-battery-status-of-bt-devices-with-monterey).

I used to use ioreg, you can have a look at [earlier commits](https://github.com/gschrader/ubersicht-bluetooth-battery-bar/tree/9449ad53e37292ad8c6e435a0f4d924dd725b428) if you want to change back to that and give it a try.
